export const SET_VIDEO = "SET_VIDEO";
export const SET_VISIBLE_VIDEO = "SET_VISIBLE_VIDEO";
export const SET_VOLUME = "SET_VOLUME";
export const SET_VIDEO_CLICKED = "SET_VIDEO_CLICKED";
export const SET_SCROLL_INTO_VIEW = "SET_SCROLL_INTO_VIEW";
export const SET_OPEN_LOGIN_MODAL = "SET_OPEN_LOGIN_MODAL";
export const SET_USER = "SET_USER";
